### ISSUE TITLE
모바일에서 댓글 작성시, 위지윅 에디터로 전환이 안됩니다.

### ISSUE THREAD

**Issue by maesiltea** [sketchbook/xe#8]
안녕하세요, 덕분에 스케치북 스킨 잘 사용하고 있습니다.
스킨 사용중에 한가지 문제점이 있어 report 드립니다. 아래 TestCase로 테스트 해 보시면 확인 가능할듯 싶습니다.
문제가 발생하는 페이지는 아래와 같습니다. 댓글은 제한이 없으니 마음껏 테스트 하셔도 무방합니다.
http://maesiltea.iptime.org/zbxe/diary/64328

TestCase
1. 스마트폰으로 게시물에 접속한다.
2. 가로모드로 회전한다.
3. 댓글 입력폼에서 '에디터 선택하기'를 눌러 '에디터 모드'를 선택한다.
결과: 페이지가 새로고침 되나, 텍스트모드 상태가 유지되며 에디터를 사용할 수 없음

바쁘시겠지만 확인좀 부탁드리겠습니다^^

**Comment by sketchbook** [comment]
댓글에서는 에디터를 사용하는 게(모바일에서는 에디터 사용 자체가 부적합하다고 하죠) 부적합해서 강제로 텍스트모드로 설정하도록 했어요.
제보 감사드립니다~
